settings:
  start_date:
    day: 11
    month: 6
    year: 2026
  simulation_days: 365
  work_day:
    start: 8
    end: 16
  employee_count: 25
  transaction_date_window: 14
  employee_timeout:
    minimum: 0.33
    maximum: 3
  employee_work_session:
    minimum: 0.25
    maximum: 2
  employee_work_break: 4
  employee_clarification_wait:
    minimum: 1
    maximum: 24
  noise_percentage: 0.05

probabilities:
  select_unassigned_incident_chance: 0.4
  select_new_incident_chance: 0.5
  sla_multiplier: 1
  incident_high_priority_threshold: 0.25
  hand_over_chance: 0.85
  base_clarification_chance: 0.2
  incident_resolution_sessions_weight: 0.15
  incorrect_field_chance: 0.01
  fraud_clarify_multiplier: 5
  clarification_retry_chance: 0.15
  clarification_retry_decay: 0.5
  base_reassign_chance: 0.05
  base_cancel_chance: 0.01
  incident_blowup_chance: 0.05

weights:
  providers:
    TSYS: 0.65
    NOT_APPLICABLE: 0.3
    FDR: 0.05
  priorities:
    High: 0.25
    Medium: 0.5
    Low: 0.25
  reception_channels:
    Branch: 0.125
    Complaints Book: 0.02
    Contact Center Email: 0.02
    Contact Center Phone: 0.02
    Contact Center Social Media: 0.02
    Customer Care: 0.02
    Email: 0.125
    Phone Call: 0.6
    Formal Complaint: 0.02
    Web Page (Complaints): 0.03
  missing_fields:
    customerlegalrep: 25
    acc_transit: 25
    customeraddress: 2
    customercity: 2
    customerbphoneno: 1
  root_causes: 
    Claims: 
      Procedure / Process: 0.55
      System: 0.3
      Fraud: 0.1
      Behaviour: 0.035
      ABM / ATM: 0.015
    Requests:
      Procedure / Process: 0.7
      Fraud: 0.125
      Behaviour: 0.125
      Suitability: 0.035
      System: 0.015
    Complaints:
      Procedure / Process: 0.65
      System: 0.085
      Behaviour: 0.085
      Service Issues: 0.07
      Miscommunication / Misunderstanding: 0.055
      Unfounded: 0.055
  clarification_reasons:
    Missing Information: 0.8
    Inform Customer: 0.1
    Missing Documentation: 0.1
  factor_decays:
    Sessions: 0.6
    Clarifications: 0.6